
services:
  user-service:
    build:
      context: .
      dockerfile: user-service/Dockerfile
    ports:
      - "3001:3001"

  menu-db:
    image: postgres:15
    container_name: menu-db
    environment:
      POSTGRES_DB: menudb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  menu-service:
    build:
      context: .
      dockerfile: menu-service/Dockerfile
    ports:
      - "3002:3002"
    environment:
      DATABASE_URL: postgres://postgres:password@menu-db:5432/menudb?sslmode=disable
    depends_on:
      menu-db:
        condition: service_healthy

  cart-db:
    image: postgres:15
    container_name: cart-db
    environment:
      POSTGRES_DB: cartdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5434:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  cart-service:
    build:
      context: .
      dockerfile: cart-service/Dockerfile
    ports:
      - "3005:3005"
    environment:
      DATABASE_URL: postgres://postgres:password@cart-db:5432/cartdb?sslmode=disable
    depends_on:
      cart-db:
        condition: service_healthy
    

  order-service:
    build:
      context: .
      dockerfile: order-service/Dockerfile
    ports:
      - "3003:3003"

  payment-service:
    build:
      context: .
      dockerfile: payment-service/Dockerfile
    ports:
      - "3004:3004"