services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: foodhub
    ports:
      - "5432:5432"

  user-service:
    build:
      context: .
      dockerfile: user-service/Dockerfile
    ports:
      - "3001:3001"
    depends_on:
      - postgres

  menu-service:
    build:
      context: .
      dockerfile: menu-service/Dockerfile
    ports:
      - "3002:3002"
    depends_on:
      - postgres

  order-service:
    build:
      context: .
      dockerfile: order-service/Dockerfile
    ports:
      - "3003:3003"
    depends_on:
      - postgres
      - user-service
      - menu-service

  payment-service:
    build:
      context: .
      dockerfile: payment-service/Dockerfile
    ports:
      - "3004:3004"
    depends_on:
      - postgres
      - order-service

  cart-service:
    build:
      context: .
      dockerfile: cart-service/Dockerfile
    ports:
      - "3005:3005"
    depends_on:
      - user-service
      - menu-service

  # api-gateway:
  #   build:
  #     context: .
  #     dockerfile: api-gateway/Dockerfile
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - user-service
  #     - menu-service
  #     - order-service
  #     - payment-service
